[gin]
requestseconds = 10

[server]
shutdownseconds = 5

[server.http]
port = "8080"

[postgres]
username = "todo_service"
host = "localhost"
port = "5432"
dbname = "todo"
sslmode = "disable"

[lfu]
capacities = { "todo" = 10 }

[jwt]
tokenminutes = 15

[hashids]
salts = { "user" = "lVNhX9FzCOAy0rHP", "todo" = "stWLM0rFHEbpINHg" }
hashlengths = { "user" = 6, "todo" = 6 }

[bcrypt]
cost = 12

[logrus]
format = "text"