logformatting = "Text"
requestseconds = 10
shutdownseconds = 5

[server.http]
port = "8080"

[postgres]
username = "todo_service"
host = "localhost"
port = "5432"
dbname = "todo"
sslmode = "disable"

[jwt]
minutesttl = 15

[hashids]
hashlength = 6
salts = { "todo" = "stWLM0rFHEbpINHg", "user" = "lVNhX9FzCOAy0rHP"}

[bcrypt]
cost = 12
